# Generated by Django 3.2.5 on 2021-08-03 02:25

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(default=0),
            preserve_default=False,
        ),
    ]
